# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\varfolomey\Desktop\terver_lab2_task4_v1\LR2_task4\ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.neededHypotises = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.neededHypotises.setFont(font)
        self.neededHypotises.setObjectName("neededHypotises")
        self.neededHypotises.setColumnCount(1)
        self.neededHypotises.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.neededHypotises.setHorizontalHeaderItem(0, item)
        self.horizontalLayout_3.addWidget(self.neededHypotises)
        self.probability = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.probability.setFont(font)
        self.probability.setObjectName("probability")
        self.probability.setColumnCount(1)
        self.probability.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.probability.setHorizontalHeaderItem(0, item)
        self.horizontalLayout_3.addWidget(self.probability)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.formulaLabel = QtWidgets.QLabel(self.centralwidget)
        self.formulaLabel.setObjectName("formulaLabel")
        self.verticalLayout.addWidget(self.formulaLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.numberLabel = QtWidgets.QLabel(self.centralwidget)
        self.numberLabel.setObjectName("numberLabel")
        self.horizontalLayout_2.addWidget(self.numberLabel)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox.setFont(font)
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.resultLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel.setObjectName("resultLabel")
        self.horizontalLayout.addWidget(self.resultLabel)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.solveButton = QtWidgets.QPushButton(self.centralwidget)
        self.solveButton.setObjectName("solveButton")
        self.verticalLayout.addWidget(self.solveButton)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Full Prabability & Bayes Formula"))
        item = self.neededHypotises.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hypotises"))
        item = self.probability.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Probabilities"))
        self.formulaLabel.setText(_translate("MainWindow", "TextLabel"))
        self.numberLabel.setText(_translate("MainWindow", "Количество гипотез"))
        self.resultLabel.setText(_translate("MainWindow", "Результат"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Формула полной верятности"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Формула Бейеса"))
        self.solveButton.setText(_translate("MainWindow", "Решить"))
